### ISSUE TITLE
FeatureReq - Offset for MIDI notes (aka "shift octave")

### ISSUE THREAD

**Issue by 1000tongues** [tttapa/MIDI_controller#59]
Hello, and thanks for both this library and the thorough explanations of how to flash on an Uno (works perfectly)!

Feature request: I've tried a 5x5 ButtonMatrix on my Uno, which works fine. Planning to hack together a two-octave keyboard controller. However, I'd like to be able to step the octave up and down - meaning, press a button, subsequently add 12 to all note values. Press another, subsequently subtract 12.

Is this possible?

Arduino UNO
**MIDI Controller library**: ? 3.1.0 ?  
**Arduino IDE**: ? 1.8.5 ?  
**Operating System**: ? Windows ?  
**Operating System version**: ? 10 ?

**Comment by tttapa** [comment]
This feature is implemented in the next big release of my Control Surface library.

That part is more or less finished, but the API has changed completely, and I haven't documented it yet. 
If you're brave, you can look through the new examples (there aren't many yet) and the source code.

https://github.com/tttapa/Control-Surface/blob/revision-4/examples/Transpose/Transpose/Transpose.ino

The same can be achieved using banks of width 12 and bankselectors. However, keep in mind that the MIDI_Controller library does not fully support banking of button matrices (IIRC) because you run into trouble when trying to change the bank while a button is pressed.  
This issue has been resolved in the Control Surface library.
